# changelog:
#   categories:
#   - title: Bug-Fixes
#     labels:
#     - fix
#     - bug
#     - bugfix
#   - title: New Features
#     labels:
#     - feature
#     - enhancement
#   - title: Other Changes
#     labels:
#        - “*”

changelog:
  categories:
    - title: Features
      labels:
        - feature
    - title: Bug Fixes
      labels:
        - fix
        - fixes
        - bugfix
        - bugfixes
    - title: Other changes
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - feature
          - fix
          - fixes
          - bugfix
          - bugfixes